on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2 
      
      - name: Deploy in EC2
        env: 
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.AWS_HOST }}
          USER_NAME: ${{ secrets.AWS_USERNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          echo $PRIVATE_KEY
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd /var/www/html/smartcostmanagement &&
            git config --global --add safe.directory /var/www/html/smartcostmanagement &&
            git pull origin main '
